### ISSUE TITLE
About the purpose of Webflux

### ISSUE THREAD

**Issue by HelloTo4x** [AlexanderBanar/weather#1]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by AlexanderBanar** [comment]
> Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

Hi, the purpose of my project is just to taste WebFlux :) within a simple web-app. Of course, mainly it is used to increase performance as the Reactor Project realizes the non-blocking model. I'm far not an expert in WebFlux but I believe it is not ideal and has its own pros and cons as well. First disad that comes to my thought is.. maybe compatibility.. of various deployment platforms i.e. Servlet containers (like Jetty, Tomcat, Undertow, and it's case is Netty) though solutions are all over there now (adapters).
